/* Project content is kept separate so the interface can switch languages cleanly. */
window.PORTFOLIO_PROJECTS = [
  {
    id: "ecommerce",
    title: { es: "E-commerce full stack", en: "Full-stack e-commerce" },
    category: "development",
    categoryLabel: { es: "Desarrollo web", en: "Web development" },
    description: {
      es: "Una experiencia de compra completa, del catálogo al panel de administración.",
      en: "A complete shopping experience, from the catalog to the admin dashboard.",
    },
    detail: {
      es: "Plataforma de comercio electrónico con carrito de compras, catálogo dinámico, filtros avanzados y soporte PWA. Desarrollada con una arquitectura limpia y una base de datos relacional.",
      en: "An e-commerce platform with a shopping cart, dynamic catalog, advanced filters and PWA support. Built with a clean architecture and a relational database.",
    },
    tags: [
      "React & Vite",
      "Node.js / Express",
      "Prisma / PostgreSQL",
      "TypeScript",
    ],
    repo: "https://github.com/LUCKYTANO765/ecommerce",
    visual: "commerce",
    featured: true,
  },
  {
    id: "supercasino365",
    title: { es: "SuperCasino365", en: "SuperCasino365" },
    category: "development",
    categoryLabel: { es: "Plataforma full stack", en: "Full-stack platform" },
    description: {
      es: "Una plataforma de juegos con backend en Go, gestión de roles y pruebas de extremo a extremo.",
      en: "A gaming platform with a Go backend, role management and end-to-end testing.",
    },
    detail: {
      es: "Plataforma con póker, blackjack y slots, además de roles para cajeros y clientes. Backend migrado de Node.js y Prisma a Go, despliegue en VPS y pruebas QA E2E con Playwright.",
      en: "A platform with poker, blackjack and slots, plus cashier and client roles. The backend was migrated from Node.js and Prisma to Go, with VPS deployment and Playwright E2E testing.",
    },
    tags: ["React", "Go (Golang)", "Playwright", "VPS Deploy"],
    repo: null,
    visual: "platform",
    featured: true,
  },
  {
    id: "century21",
    title: { es: "Reclutamiento · Century 21", en: "Recruiting · Century 21" },
    category: "automation",
    categoryLabel: { es: "Automatización e IA", en: "Automation & AI" },
    description: {
      es: "Búsqueda de candidatos, filtros de perfiles y conversaciones de contratación en WhatsApp.",
      en: "Candidate discovery, profile screening and hiring conversations through WhatsApp.",
    },
    detail: {
      es: "Bot de reclutamiento construido con n8n para Century 21. Conecta la búsqueda y el filtrado de candidatos con la gestión automatizada de conversaciones por WhatsApp.",
      en: "A recruiting bot built with n8n for Century 21. It connects candidate discovery and screening with automated conversation management through WhatsApp.",
    },
    tags: ["n8n", "WhatsApp API", "AI Agents", "APIs REST"],
    repo: null,
    visual: "workflow",
    featured: true,
  },
  {
    id: "parental-control",
    title: { es: "Control parental & juegos", en: "Parental control & games" },
    category: "security",
    categoryLabel: { es: "Seguridad y juego", en: "Security & play" },
    description: {
      es: "Juegos interactivos y control parental para acompañar el tiempo frente a la pantalla.",
      en: "Interactive games and parental controls to guide time spent on screen.",
    },
    detail: {
      es: "Aplicación de control parental integrada con dinámicas de juegos interactivos para restringir y guiar de manera lúdica el tiempo en pantalla y los accesos.",
      en: "A parental control application coupled with interactive learning games to dynamically restrict and guide screen time and network access.",
    },
    tags: ["Node.js", "Security API", "CSS3 Grid", "JS"],
    repo: null,
    visual: "play",
    featured: true,
  },
  {
    id: "mortalsoft",
    title: { es: "MortalSoft Casino Suite", en: "MortalSoft Casino Suite" },
    category: "games",
    categoryLabel: { es: "Desarrollo de juegos", en: "Game development" },
    description: {
      es: "Minijuegos de slots y crash con lógica probabilística e interfaces en tiempo real.",
      en: "Slots and crash minigames with probability logic and real-time interfaces.",
    },
    detail: {
      es: "Suite de minijuegos interactivos de casino, con simuladores de tragamonedas y juegos tipo Aviador. Combina lógica probabilística con interfaces responsivas en tiempo real.",
      en: "A suite of interactive casino minigames, including slots and Aviator-style crash simulators. It combines probability logic with responsive, real-time interfaces.",
    },
    tags: ["JavaScript", "HTML5 Canvas", "CSS3", "Git"],
    repo: null,
    visual: "play",
    featured: false,
  },
  {
    id: "tower-auditoria",
    title: { es: "Tower Auditoría", en: "Tower Audit" },
    category: "games",
    categoryLabel: { es: "Físicas y QA", en: "Physics & QA" },
    description: {
      es: "Un juego de físicas con herramientas para inspeccionar colisiones y errores del motor.",
      en: "A physics game with tools to inspect collisions and engine errors.",
    },
    detail: {
      es: "Juego interactivo desarrollado con React y Matter.js. Integra un panel de auditoría para validar colisiones, probar distorsiones físicas e inspeccionar fallos lógicos del motor.",
      en: "An interactive stacking game developed with React and Matter.js. It includes an audit panel for validating collisions, testing physical distortions and inspecting engine logic errors.",
    },
    tags: ["React", "Matter.js", "Vite", "QA Logic"],
    repo: null,
    visual: "play",
    featured: false,
  },
  {
    id: "tower-rush-3d",
    title: { es: "Tower Rush 3D", en: "Tower Rush 3D" },
    category: "games",
    categoryLabel: { es: "Desarrollo 3D", en: "3D development" },
    description: {
      es: "Defensa de torres en tres dimensiones, con combate dinámico y rutas de enemigos.",
      en: "Three-dimensional tower defense with dynamic combat and enemy pathfinding.",
    },
    detail: {
      es: "Juego tridimensional del género Tower Rush. Implementa mecánicas de defensa, búsqueda de rutas de enemigos y renderizado de gráficos 3D en tiempo real.",
      en: "A three-dimensional Tower Defense / Tower Rush game. It implements defense mechanics, enemy pathfinding and real-time 3D rendering.",
    },
    tags: ["C#", "Unity 3D", "3D Physics", "Git"],
    repo: null,
    visual: "play",
    featured: false,
  },
  {
    id: "casino-qa",
    title: { es: "Casino E2E Test Suite", en: "Casino E2E Test Suite" },
    category: "automation",
    categoryLabel: { es: "Automatización de QA", en: "QA automation" },
    description: {
      es: "Pruebas automatizadas de juegos, transacciones e interrupciones de red.",
      en: "Automated testing for games, transaction flows and network interruptions.",
    },
    detail: {
      es: "Marco de pruebas E2E para validar la lógica probabilística de tragamonedas y juegos tipo crash, con flujos de transacciones y cortes de red simulados.",
      en: "An E2E test framework for validating probability logic in slots and crash games, covering transaction flows and simulated network interruptions.",
    },
    tags: ["Playwright", "Jest", "TypeScript", "GitHub Actions"],
    repo: null,
    visual: "code",
    featured: false,
  },
  {
    id: "local-llm",
    title: { es: "Orquestación de LLM locales", en: "Local LLM orchestration" },
    category: "automation",
    categoryLabel: { es: "IA local", en: "Local AI" },
    description: {
      es: "Modelos Llama y Qwen desplegados de forma privada con agentes y flujos de trabajo propios.",
      en: "Privately deployed Llama and Qwen models with agents and custom workflows.",
    },
    detail: {
      es: "Configuración y despliegue local de modelos de lenguaje como Llama y Qwen, con orquestación de agentes y flujos de trabajo para ejecutarlos de forma privada.",
      en: "Private configuration and local hosting of language models such as Llama and Qwen, with agent orchestration and customized offline coding pipelines.",
    },
    tags: ["Local LLMs", "AI Agents", "LM Studio", "Python"],
    repo: null,
    visual: "workflow",
    featured: false,
  },
  {
    id: "osint-pentesting",
    title: { es: "OSINT & pentesting", en: "OSINT & pentesting" },
    category: "security",
    categoryLabel: { es: "Seguridad ofensiva", en: "Offensive security" },
    description: {
      es: "Reconocimiento, auditorías de aplicaciones y pruebas de seguridad web.",
      en: "Reconnaissance, application audits and web security testing.",
    },
    detail: {
      es: "Reconocimiento OSINT, pruebas de penetración web y campañas de phishing controladas para concientización en seguridad. Incluye informática forense y auditorías con Burp Suite, OWASP ZAP y Nmap.",
      en: "OSINT reconnaissance, web penetration testing and controlled phishing campaigns for security awareness. Includes computer forensics and audits using Burp Suite, OWASP ZAP and Nmap.",
    },
    tags: ["Burp Suite", "OWASP ZAP", "Nmap", "Python"],
    repo: null,
    visual: "security",
    featured: false,
  },
  {
    id: "pax-medica",
    title: { es: "Pax Médica", en: "Pax Médica" },
    category: "development",
    categoryLabel: { es: "Web de salud", en: "Healthcare website" },
    description: {
      es: "Una landing para una clínica estética, con reserva de citas y diseño pensado para móviles.",
      en: "An aesthetic clinic landing page with appointment booking and a mobile-first design.",
    },
    detail: {
      es: "Landing page para una clínica de cirugía plástica, procedimientos estéticos y tratamientos de inyecciones para bajar de peso. Enfocada en confianza, reserva de citas y experiencia móvil.",
      en: "A landing page for a plastic surgery clinic offering aesthetic procedures and weight-loss injection treatments. Focused on trust, appointment booking and the mobile experience.",
    },
    tags: ["React", "TailwindCSS", "Responsive", "SEO"],
    repo: null,
    visual: "code",
    featured: false,
  },
  {
    id: "medicare-deportes",
    title: { es: "MediCare & Deportes", en: "MediCare & Sports" },
    category: "development",
    categoryLabel: { es: "Experiencias web", en: "Web experiences" },
    description: {
      es: "Landings médicas y portales deportivos con estadísticas y marcadores actualizados.",
      en: "Medical landing pages and sports portals with updated statistics and scores.",
    },
    detail: {
      es: "Desarrollo de landing pages médicas y plataformas web de deportes interactivos, con estadísticas y tablas de marcadores actualizados.",
      en: "Bespoke medical landing pages and interactive sports portals with statistics and live score tables.",
    },
    tags: ["React", "TypeScript", "TailwindCSS", "SEO"],
    repo: null,
    visual: "platform",
    featured: false,
  },
];
